# Generated by Django 3.1.2 on 2020-10-22 16:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Stock', '0002_auto_20201022_1135'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='merge',
            table='merge',
        ),
    ]
