# Generated by Django 3.1.2 on 2020-10-26 00:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Stock', '0003_auto_20201022_1647'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='merge',
            table='MERGE',
        ),
    ]
