-- SHOW DATABASES;
-- USE investar;-- 
-- SELECT * FROM company_info;
-- SELECT * FROM daily_price;
-- DROP	DATABASE investar
-- 
-- CREATE DATABASE Media;
-- USE Media;

# talbe 생성
-- CREATE TABLE S1(_id INT AUTO_INCREMENT COMMENT '순번',
-- filename		CHAR(14) 	NOT NULL 		COMMENT '파일명',
-- class01 		INT 		DEFAULT 0			COMMENT '안전벨트 착용',
-- class02 		INT 		DEFAULT 0			COMMENT '안전벨트 미착용',
-- class03 		INT 		DEFAULT 0			COMMENT '안전고리 착용',
-- class04 		INT 		DEFAULT 0			COMMENT '안전고리 미착용',
-- class05 		INT 		DEFAULT 0			COMMENT '안전화 착용',
-- class06 		INT 		DEFAULT 0			COMMENT '안전화 미착용',
-- class07 		INT 		DEFAULT 0			COMMENT '안전모 착용',
-- class08 		INT 		DEFAULT 0			COMMENT '안전모 미착용',
-- class09 		INT 		DEFAULT 0			COMMENT '포크레인',
-- class10 		INT 		DEFAULT 0			COMMENT '페이로다',
-- class11 		INT 		DEFAULT 0			COMMENT '지게차',
-- class12 		INT 		DEFAULT 0			COMMENT '덤프트럭',
-- class13 		INT 		DEFAULT 0			COMMENT '레미콘',
-- class14 		INT 		DEFAULT 0			COMMENT '펌프카',
-- class15 		INT 		DEFAULT 0			COMMENT '항타기',
-- class16 		INT 		DEFAULT 0			COMMENT '트럭',
-- class17 		INT 		DEFAULT 0			COMMENT '고소작업대',
-- class18 		INT 		DEFAULT 0			COMMENT '타워크레인',
-- class19 		INT 		DEFAULT 0			COMMENT '스카이',
-- class20 		INT 		DEFAULT 0			COMMENT '갱폼',
-- class21 		INT 		DEFAULT 0			COMMENT '알폼',
-- class22 		INT 		DEFAULT 0			COMMENT 'A형 사다리',
-- class23 		INT 		DEFAULT 0			COMMENT '우마',
-- class24 		INT 		DEFAULT 0			COMMENT '분전반',
-- class25 		INT 		DEFAULT 0			COMMENT '개구부 덮개',
-- class26 		INT 		DEFAULT 0			COMMENT '위험물 보관소',
-- class27 		INT 		DEFAULT 0			COMMENT 'ELEV, 추락방지망',
-- class28 		INT 		DEFAULT 0			COMMENT '호이스트',
-- class29 		INT 		DEFAULT 0			COMMENT '잭서포트',
-- class30 		INT 		DEFAULT 0			COMMENT '강관비계',
-- class31 		INT 		DEFAULT 0			COMMENT '시스템 비계',
-- class32 		INT 		DEFAULT 0			COMMENT '시멘트 벽돌',
-- class33 		INT 		DEFAULT 0			COMMENT '망치',
-- class34 		INT 		DEFAULT 0			COMMENT '전동드릴',
-- class35 		INT 		DEFAULT 0			COMMENT '레미탈',
-- class36 		INT 		DEFAULT 0			COMMENT '치장블럭',
-- class37 		INT 		DEFAULT 0			COMMENT '믹서기',
-- class38 		INT 		DEFAULT 0			COMMENT 'H빔',
-- class39 		INT 		DEFAULT 0			COMMENT '고속절단기',
-- class40 		INT 		DEFAULT 0			COMMENT '바이브레이터',
-- class41 		INT 		DEFAULT 0			COMMENT '소화기',
-- class42 		INT 		DEFAULT 0			COMMENT '용접기',
-- class43 		INT 		DEFAULT 0			COMMENT '핸드그라인더',
-- class44 		INT 		DEFAULT 0			COMMENT '핸드카',
-- class45 		INT 		DEFAULT 0			COMMENT '불티방지막',
-- BB				INT 		DEFAULT 0			COMMENT 'Bounding Box',
-- PO				INT		DEFAULT 0			COMMENT 'Polygon',
-- KP				INT		DEFAULT 0			COMMENT 'Key-Point',
-- 
-- PRIMARY KEY(_id, filename)
-- ) COMMENT '공사';
-- 

-- SHOW TABLES;
SELECT * FROM s1;